### ISSUE TITLE
Remove global package manager?

### ISSUE THREAD

**Issue by joehillen** [joehillen/craft#2]
I'm considering removing the global/generalized package manager from craft.

Currently, when running craft you have to specify a `PackageManager`. My original reasoning is that users should be able to share a module that requires packages and have it just work in most cases. For example:

```haskell
module Main where

import Control.Monad.Logger (runStdoutLoggingT)
import Craft
import Craft.Apt (apt)

main :: IO ()
main = do
  runStdoutLoggingT $
    runCraft runLocal (craftEnv apt) $ do
      exec_ "hostname" []
      craftCurl
    
craftCurl :: Craft ()
craftCurl = do
  craft_ $ package "curl"
```

The hope is that `craftCurl` can be shared between different platforms and it should work in most cases.

But assumptions start to break down: 

  * **What if the package does not have the same name on every platform?** Packages having the same name in different distros often feels like the exception rather than the rule.
  * **Not every craft configuration will install a package.** For example, why do I need to specify a package manager if I only want to see the output of `hostname`?
  * **A package isn't always just a `name` and a `version` on every distro?** Any extra information should be represented in the types rather than overloaded in the `name` and `version`. Extra information, such as:
    * A repo like on Arch, e.g. `community/curl` or `aur/curl`
    * A distro version like on Fedora, e.g. `f24` or `f25`
    * A version **and** a hash on Nix.
  * **What if you have multiple package managers on the same host?**

My plan is to remove `PackageManager` from `craftEnv` and have different `Package` types
in each module such as `Craft.Apt` and `Craft.DNF` with their own `Craftable` instances.  
I think I should keep the generalized `Package` and `PackageManager` types in `Craft.Package` but `package` should require a `PackageManager`.

```haskell
module Craft.Package where

data Package
   = Package
   { pkgManager :: PackageManager
   , pkgName    :: String
   , pkgVersion :: Version
   }
   
package :: PackageManager -> String -> Package
package pm name =
  Pacakge
  { pkgManager = pm
  , pkgName    = name
  , pkgVersion = AnyVersion
  }
```

The top example becomes:

```haskell
module Main where

import Control.Monad.Logger (runStdoutLoggingT)
import Craft
import Craft.Apt (apt)
import Craft.Package (PackageManager, package)

main :: IO ()
main = do
  runStdoutLoggingT $
    runCraft runLocal craftEnv $ do
      exec_ "hostname" []
      craftCurl apt
    
craftCurl :: PackageManger -> Craft ()
craftCurl pm = do
  craft_ $ package pm "curl"
```

This is nice because now it's explicit in the types that `craftCurl` requires a `PackageManager` in order to work.

**Comment by joehillen** [comment]
@drewr @michaelbaamonde @dakrone @tylerjl

I'd love to hear if you have any thoughts since you're my only "users"

**Comment by dakrone** [comment]
I'd love something that is like (excuse the lisp, translate the pseudo-code into haskell):

```clj
(with-package-manager apt
  (craft-package "curl")
  (craft-package "tcpdump"))
(with-package-manager pip
  (craft-package "youtube-dl"))
```

**Comment by dakrone** [comment]
What could be really nice is that if you made `with-package-manager` check for the existence of the package manager and make the body a noop in the event it doesn't exist, this would allow you to do:

```clj
(with-package-manager apt
  (craft-package "mpd"))
(with-package-manager dnf
  (craft-package "Mpd"))
```

And have it work, regardless of which package manager is used (think maybe `easy_install` versus  `pip`?)

Just brainstorming, I'm curious what others think :)

**Comment by drewr** [comment]
Specializing on the `PackageManager` impl feels right to me.  And I think you could do what @dakrone wants with a little function like `withPM :: PackageManager -> [Package]` or something more monadic with do-syntax if the simple type isn't enough.

**Comment by joehillen** [comment]
@dakrone I'd call any implicit noop a "foot-gun", especially in config management, but you're basically describing the current behaviour.

Currently `CraftEnv` is passed around using the `Reader` monad, which means you can override the package manager like this:

```haskell
withPackageManager :: PackageManager -> Craft a -> Craft a
withPackageManager pm = local (\ce -> ce { _craftPackageManager = pm })
-- Turns out I'd forgotten to include this function because I've personally never needed it.

main :: IO ()
main = do
  runStdoutLoggingT $
    runCraft runLocal (craftEnv apt) $ do
      exec_ "hostname" []
      craft_ $ package "curl"
      withPackageManager pip $ 
        craft_ $ package "some-python-package"
      withPackageManager npm $ 
        craft_ $ package "leftpad"
```

My intent for any frankenstein package manager that changes behaviour based on which packages managers are available is that you would create a new `PackageManager` that is a composition of the various other package managers. It could also do package name translation. Your noop behaviour could be implemented there as well. The pieces are not hard to glue together.

---

Under the proposed changes, you could still use the `Reader` monad to pass around the package manager:

```haskell
withPackageManager :: Monad m => PackageManager -> Reader PackageManager m -> Reader PackageManger m
withPackageManager pm = local (const pm)

package :: Monad m => String -> Reader PackageManager m
package name = do
  pm <- ask
  return $
    Package
    { pkgManager = pm
    , pkgName    = name
    , pkgVersion = AnyVersion
    }

main :: IO ()
main = do
  runStdoutLoggingT $
    runCraft runLocal craftEnv $ do
      exec_ "hostname" []
      runReader apt $ do 
        curl <- package "curl"
        liftM $ craft_ curl
        withPackageManager pip $ do
          somePythonPackage <- package "some-python-package"
          liftM $ craft_ $ somePythonPackage
        withPackageManager npm $ do
          leftpad <- package "leftpad"
          liftM $ craft_ leftpad
```

This is a perverse example but I hope you get the idea. The problem with this is that anything in the `Craft a` DSL needs to be prefixed with `liftM` in order to turn it into a `Reader PackageManager (Craft a)`.

Because of this the ergonomics end up being worse than explicitly passing around a package manager as input.

In my hands-on experiences, you typically just install packages all at once near the beginning of your configuration so there isn't much need to have the package manager passed all over the place.

-----
Under the proposed changes, in the case where you want to change the package name based on platform, you can do that either in the `PackageManager`...

```haskell
aptOrDnf :: PackageManager
aptOrDnf =
  PackageManger
  { pmInstaller =
      \(name, version) -> do
        platform <- fact "lsbdistid"
        let name' =
              case (platform, name) of
                ("Fedora", "mpd") -> "Mpd"
                ("Debian", "Mpd") -> "mpd"
                (_,        n)     -> n
        let install = 
              case platform of
                "Debian" -> Apt.install
                "Fedora" -> DNF.install
                x        -> error $ "Unsupported supported platform: "++x
        install name'
        ...
  , ...}
  
installMpd :: Craft ()
installMpd = do
  craft_ $ package aptOrDnf "mpd"
```

or inline in the script...

```haskell
installMpd :: Craft ()
installMpd = do
  platform <- fact "lsbdistid"
  case platform of
    "Debian" -> craft_ $ package apt "mpd"
    "Fedora" -> craft_ $ package dnf "Mpd"
    x        -> fail $ "Unsupported supported platform: "++x
```

*Warning: I haven't type-checked any of this, so there are probably errors*

**Comment by joehillen** [comment]
> Specializing on the `PackageManager` impl feels right to me.

@drewr I don't follow. Is that a 👍 on my proposal?

**Comment by drewr** [comment]
LGTM 👍
